
// This file defines the "question bank" for the workshop.
// It maintains the original structure but refines the questions to be more user-friendly
// and incorporates the principles of Atomic Design for the UXD.

export const masterSchema = {
  prd: {
    title: 'Product Requirements Document (PRD)',
    product_overview: {
      title: '1. Product Overview & Vision',
      questions: [
        "What is the single most important problem you're trying to solve?",
        'Who is the primary audience that will benefit most from this solution?',
        'Thinking long-term, what is the ultimate vision for this project?',
      ],
    },
    core_features: {
      title: '2. Core Features & User Journeys',
      questions: [
        "Describe the single most important task or journey a user will take to solve their core problem.",
        'What are the most essential features needed to make that journey possible?',
        "To help us focus, what's a feature we should intentionally leave out of the first version?",
      ],
    },
    success_metrics: {
      title: '3. Success Metrics',
      questions: [
        'How will you know if this project is a success?',
        'What is the one key metric we should measure for the first version?',
      ],
    },
    future_roadmap: {
      title: '4. Future Roadmap',
      questions: [
        "Looking beyond the first version, what's one thing you'd be excited to add next?",
      ],
    },
  },
  edd: {
    title: 'Engineering Design Document (EDD)',
    technical_overview: {
      title: '1. Technical Overview',
      questions: [
        "In simple terms, how do you envision this being built? (e.g., 'A modern web app', 'a mobile app'?)",
        'Are there any key integrations with other services or APIs we need to consider?',
      ],
    },
    key_considerations: {
      title: '2. Key Considerations',
      questions: [
        'Will users need to create an account and log in?',
        'Are there any specific security or data privacy concerns we need to be aware of?',
        'What kind of information will the app need to remember or save for the user?',
      ],
    },
  },
  uxd: {
    title: 'User Experience Document (UXD) - A Design System Approach',
    design_atoms: {
      title: '1. Core Design Language (Atoms)',
      questions: [
        "Let's start building your design system. What is the personality or brand of your app? (e.g., 'playful', 'serious', 'modern')",
        'Based on that personality, what should the primary brand color be?',
        "And how should the text feel? (e.g., 'like a clean tech blog', 'like a classic newspaper')",
      ],
    },
    design_molecules: {
      title: '2. Key Components (Molecules)',
      questions: [
        "Now let's think about the building blocks of your UI. What are 2-3 of the most common, reusable components you'll need? (e.g., 'a search bar', 'a user profile card')",
      ],
    },
    design_templates: {
      title: '3. Page Layouts (Templates)',
      questions: [
        'How should the main page of the app be laid out? Can you describe the major sections on that page?',
        'What is the most important piece of information or action to present to the user on that main page?',
      ],
    },
  },
  pdd: {
    title: 'Privacy Design Document (PDD)',
    collection: {
      title: '1. Data Collection',
      questions: [
        'What user data is being collected at each step of any user journey? This includes data actively provided by the user (e.g., name, email during sign-up) and data generated by their activity (e.g., search history, location, usage logs).',
      ],
    },
    use: {
      title: '2. Data Use',
      questions: [
        'How is the collected data used? Does it power features, personalization, analytics, etc.? This needs to be clear for every piece of data collected within any journey.',
      ],
    },
    sharing: {
        title: '3. Data Sharing',
        questions: [
            'With whom is the data shared? This includes internal teams, other Google products, third parties, or the public.'
        ]
    },
    notice_consent_control: {
        title: '4. Notice, Consent & Control',
        questions: [
            'How are users informed about data practices (notice)? Are they asked for consent where necessary? What controls do users have over their data (e.g., settings to opt-out, ability to edit or delete data)?'
        ]
    },
    storage_access: {
        title: '5. Data Storage & Access',
        questions: [
            'Where is the data stored, and who can access it? What security measures are in place?'
        ]
    },
    retention_deletion: {
        title: '6. Data Retention & Deletion',
        questions: [
            'How long is the data kept? What are the processes for data deletion, including user-initiated deletion?'
        ]
    },
    portability: {
        title: '7. Data Portability',
        questions: [
            'Can users export their data?'
        ]
    },
    risks_mitigations: {
        title: '8. Risks & Mitigations',
        questions: [
            'What are the potential privacy risks to users (e.g., re-identification, unauthorized access) across their various interactions, and how are these risks mitigated?'
        ]
    }
  }
};

export const masterSchemaString = JSON.stringify(masterSchema, null, 2);
